version: '3.8'  
services:  
  db:
    image: postgres:17
    container_name: database
    networks:
      - market-network
    environment:
      - POSTGRES_DB=market
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_market_data:/var/lib/postgresql/data
volumes:
  postgres_market_data:

networks:
  market-network: