openapi: 3.0.3
info:
  title: Payment Service
  version: 1.0.0

servers:
  - url: http://localhost:8081

paths:
  /private/balance/{username}:
    get:
      summary: Получить баланс пользователя
      operationId: getBalance
      tags:
        - payment
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Баланс получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Ошибка получения баланса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /private/pay:
    post:
      summary: Осуществить платёж (списание баланса)
      operationId: pay
      tags:
        - payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Платёж выполнен успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Недостаточно средств или неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BalanceResponse:
      type: object
      required:
        - balance
      properties:
        balance:
          type: integer
          format: int64
          description: Текущий баланс в рублях
      additionalProperties: false
    PaymentRequest:
      type: object
      required:
        - username
        - amount
      properties:
        username:
          type: string
          description: username пользователя
        amount:
          type: integer
          format: int64
          description: Сумма к списанию в рублях
      additionalProperties: false
    PaymentResponse:
      type: object
      required:
        - success
        - remainingBalance
        - orderId
      properties:
        success:
          type: boolean
          description: Успешность платежа
        remainingBalance:
          type: integer
          format: int64
          description: Остаток баланса после списания
      additionalProperties: false
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Описание ошибки
      additionalProperties: false