spring.application.name=my-market-app
server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/market
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Пул соединений
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m

payment.service.url=http://localhost:8081

# Инициализация базы данных (опционально)
spring.sql.init.mode=always

# R2DBC логирование
logging.level.org.springframework.data.r2dbc=DEBUG


# # Полное логирование R2DBC
# logging.level.org.springframework.data.r2dbc=TRACE
# logging.level.io.r2dbc.postgresql=TRACE
# logging.level.io.r2dbc.postgresql.QUERY=TRACE
# logging.level.io.r2dbc.postgresql.PARAM=TRACE

# Формат вывода логов
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Логирование с параметрами запросов
logging.level.org.springframework.r2dbc.core=DEBUG
