spring.application.name=my-market-app
server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/market
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Пул соединений
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m

payment.service.url=http://localhost:8081

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.client.registration.keycloak.client-id=shop
spring.security.oauth2.client.registration.keycloak.client-secret=SAZ1zu8au4VelBDMGBlzWm8Vfp5qfhD2
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9000/realms/market


logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.org.springframework.web: DEBUG
logging.level.org.springframework.ru.yandex.practicum: DEBUG

spring.sql.init.mode=always

logging.level.org.springframework.data.r2dbc=DEBUG


logging.level.org.springframework.r2dbc.core=DEBUG
