spring.application.name=my-market-app
server.port=8080
spring.r2dbc.url=r2dbc:postgresql://db:5432/market
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Пул соединений
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m

payment.service.url=http://payment:8081

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

spring.security.oauth2.client.registration.keyclock.provider=keycloak
spring.security.oauth2.client.registration.keyclock.client-id=shop
spring.security.oauth2.client.registration.keyclock.client-secret=p3cSAGcINWBF0ikYyZXnH3kaQy1ni6Sf
spring.security.oauth2.client.registration.keyclock.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keyclock.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9000/realms/market


# Hibernate настройки
# или Liquibase
# Включить Liquibase
spring.liquibase.enabled=true
# Путь к changelog файлу
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Логирование с параметрами запросов
logging.level.org.springframework.r2dbc.core=DEBUG