spring.application.name=my-market-app
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db:5432/market
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate dialect для PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate настройки
# или Liquibase
# Включить Liquibase
spring.liquibase.enabled=true
# Путь к changelog файлу
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=none
pring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

