spring.application.name=my-market-app
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/market
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate dialect для PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate настройки
spring.jpa.hibernate.ddl-auto=update
pring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===== Логирование SQL =====
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core=DEBUG
